server:
  port: 20104
spring:
  application:
    name: common
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000
    timeout: 0
jwt:
  config:
    key: itcast
    ttl: 360000
