server:
  port: 20103
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20101/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    category:
      path: /category/**
    product:
      path: /product/**
    specificate:
      path: /specificate/**
    brand:
      path: /brand/**
    user:
      path: /user/**
    order:
      path: /order/**
    address:
      path: /address/**
    search:
      path: /search/**
