server:
  port: 20106

spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster‐nodes: 192.168.55.120:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20101/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}
